Repository turbomates/easybreezy, pull requests merged in 2020-04, with the labels that each got.

#71 add roles checking
  src/main/kotlin/io/easybreezy/infrastructure/ktor/Router.kt
  src/main/kotlin/io/easybreezy/infrastructure/ktor/auth/Authorization.kt
  src/main/kotlin/io/easybreezy/infrastructure/ktor/auth/Role.kt
  src/main/kotlin/io/easybreezy/project/api/Router.kt
  src/main/kotlin/io/easybreezy/project/api/controller/ProjectController.kt
  src/main/kotlin/io/easybreezy/user/api/interceptor/Auth.kt
  src/main/kotlin/io/easybreezy/user/application/Handler.kt
  src/main/kotlin/io/easybreezy/user/application/queryobject/User.kt
  src/main/kotlin/io/easybreezy/user/cli/CreateDefaultUserCommand.kt
  src/main/kotlin/io/easybreezy/user/infrastructure/auth/UserProvider.kt
  src/main/kotlin/io/easybreezy/user/model/User.kt
  src/test/kotlin/io/easybreezy/TestApiEngine.kt
  src/test/kotlin/io/easybreezy/TestData.kt
  src/test/kotlin/io/easybreezy/project/api/controller/ProjectControllerTest.kt
Labels: backend

#70 Add employee location to user details #68
  js/package-lock.json
  js/src/features/app/components/SiderMenu.tsx
  js/src/features/human-location/actions.ts
  js/src/features/human-location/components/EmployeeListItem.tsx
  js/src/features/human-location/epics.ts
  js/src/features/human-location/selectors.ts
  js/src/features/human-resouce/actions.ts
  js/src/features/human-resouce/components/EmployeeLocationEditForm.tsx
  js/src/features/human-resouce/components/EmployeeLocationList.tsx
  js/src/features/human-resouce/components/EmployeeLocationListInner.tsx
  js/src/features/human-resouce/components/LocationAssignForm.tsx
  js/src/features/human-resouce/epics.ts
  js/src/features/human-resouce/location.reducer.ts
  js/src/features/human-resouce/reducer.ts
  js/src/features/human-resouce/selectors.ts
  js/src/features/location/actions.ts
  js/src/features/location/components/LocationForm.tsx
  js/src/features/location/components/LocationsList.tsx
  js/src/features/location/components/LocationsListItem.tsx
  js/src/features/location/epics.ts
  js/src/features/location/reducer.ts
  js/src/features/location/selectors.ts
  js/src/features/location/types.d.ts
  js/src/pages/Locations.tsx
  js/src/pages/UserDetails.tsx
  js/src/services/location-api.ts
  js/src/store/root-action.ts
  js/src/store/root-epic.ts
  js/src/store/root-reducer.ts
  js/src/utils/date.ts
Labels: frontend

#52 WIP: add-project-create/edit-form
  js/package-lock.json
  js/package.json
  js/src/Routes.tsx
  js/src/features/app/components/SiderMenu.tsx
  js/src/features/project/actions.ts
  js/src/features/project/components/ProjectCreateForm.tsx
  js/src/features/project/components/ProjectDescription.tsx
  js/src/features/project/components/ProjectDescriptionForm.tsx
  js/src/features/project/components/ProjectList.tsx
  js/src/features/project/components/ProjectRoleForm.scss
  js/src/features/project/components/ProjectRoleForm.tsx
  js/src/features/project/components/ProjectRoleFormTableWrapper.tsx
  js/src/features/project/components/ProjectSideMenu.tsx
  js/src/features/project/components/ProjectStatusForm.scss
  js/src/features/project/components/ProjectStatusForm.tsx
  js/src/features/project/epics.ts
  js/src/features/project/helpers.ts
  js/src/features/project/project.reducer.ts
  js/src/features/project/project.scss
  js/src/features/project/projects.reducer.ts
  js/src/features/project/reducer.ts
  js/src/features/project/selectors.ts
  js/src/features/project/types.d.ts
  js/src/hooks/useClearState.ts
  js/src/layouts/Project.tsx
  js/src/pages/ProjectPage.tsx
  js/src/pages/ProjectRolePage.tsx
  js/src/pages/ProjectsPage.tsx
  js/src/services/index.ts
  js/src/services/project-api.ts
  js/src/store/root-action.ts
  js/src/store/root-epic.ts
  js/src/store/root-reducer.ts
Labels: WIP, frontend

#72 add user creation #62
  doc/Location.md
  doc/User.md
  src/main/kotlin/io/easybreezy/hr/application/hr/subscriber/UserSubscriber.kt
  src/main/kotlin/io/easybreezy/infrastructure/event/user/Hired.kt
  src/main/kotlin/io/easybreezy/infrastructure/ktor/Response.kt
  src/main/kotlin/io/easybreezy/infrastructure/ktor/Validation.kt
  src/main/kotlin/io/easybreezy/infrastructure/ktor/auth/Role.kt
  src/main/kotlin/io/easybreezy/infrastructure/serialization/InferSerializer.kt
  src/main/kotlin/io/easybreezy/user/api/Router.kt
  src/main/kotlin/io/easybreezy/user/api/controller/UserController.kt
  src/main/kotlin/io/easybreezy/user/application/Archive.kt
  src/main/kotlin/io/easybreezy/user/application/Create.kt
  src/main/kotlin/io/easybreezy/user/application/Handler.kt
  src/main/kotlin/io/easybreezy/user/application/Invite.kt
  src/main/kotlin/io/easybreezy/user/application/Validation.kt
  src/main/kotlin/io/easybreezy/user/application/queryobject/User.kt
  src/main/kotlin/io/easybreezy/user/model/User.kt
  src/migrations/kotlin/io/easybreezy/migrations/V20200420120448__ChangeUserStatuses.kt
  src/test/kotlin/io/easybreezy/TestData.kt
  src/test/kotlin/io/easybreezy/user/api/controller/UserControllerTest.kt
Labels: backend

#79 rename roles to activities, add update activities
  doc/User.md
  src/main/kotlin/io/easybreezy/infrastructure/ktor/auth/Authorization.kt
  src/main/kotlin/io/easybreezy/infrastructure/ktor/auth/Role.kt
  src/main/kotlin/io/easybreezy/infrastructure/ktor/auth/Sessions.kt
  src/main/kotlin/io/easybreezy/project/api/Router.kt
  src/main/kotlin/io/easybreezy/user/api/Router.kt
  src/main/kotlin/io/easybreezy/user/api/controller/UserController.kt
  src/main/kotlin/io/easybreezy/user/api/interceptor/Auth.kt
  src/main/kotlin/io/easybreezy/user/application/Create.kt
  src/main/kotlin/io/easybreezy/user/application/Handler.kt
  src/main/kotlin/io/easybreezy/user/application/Invite.kt
  src/main/kotlin/io/easybreezy/user/application/UpdateActivities.kt
  src/main/kotlin/io/easybreezy/user/application/Validation.kt
  src/main/kotlin/io/easybreezy/user/application/queryobject/User.kt
  src/main/kotlin/io/easybreezy/user/cli/CreateDefaultUserCommand.kt
  src/main/kotlin/io/easybreezy/user/infrastructure/auth/UserProvider.kt
  src/main/kotlin/io/easybreezy/user/model/User.kt
  src/migrations/kotlin/io/easybreezy/migrations/V20200422141342__RenameRolesToActivities.kt
  src/test/kotlin/io/easybreezy/TestApiEngine.kt
  src/test/kotlin/io/easybreezy/TestData.kt
  src/test/kotlin/io/easybreezy/project/api/controller/ProjectControllerTest.kt
  src/test/kotlin/io/easybreezy/user/api/controller/UserControllerTest.kt
Labels: backend

#74 Change timetable
  doc/Location.md
  js/package-lock.json
  js/package.json
  js/src/components/antd/DatePicker.tsx
  js/src/components/antd/generateConfig.ts
  js/src/constants.ts
  js/src/features/human-resouce/absences.reducer.ts
  js/src/features/human-resouce/actions.ts
  js/src/features/human-resouce/components/EmployeeLocationEditForm.tsx
  js/src/features/human-resouce/components/EmployeeLocationList.tsx
  js/src/features/human-resouce/components/HumanResourceCalendar.scss
  js/src/features/human-resouce/components/HumanResourceCalendar.tsx
  js/src/features/human-resouce/components/HumanResourceCalendar/HumanResourceCalendar.scss
  js/src/features/human-resouce/components/HumanResourceCalendar/HumanResourceCalendar.tsx
  js/src/features/human-resouce/components/HumanResourceCalendar/HumanResourceCalendarDay.tsx
  js/src/features/human-resouce/components/HumanResourceCalendar/HumanResourceCalendarUser.tsx
  js/src/features/human-resouce/components/HumanResourceCalendar/helpers.ts
  js/src/features/human-resouce/components/HumanResourceCalendar/reducer.ts
  js/src/features/human-resouce/components/HumanResourceCalendarGroup.scss
  js/src/features/human-resouce/components/HumanResourceCalendarGroup.tsx
  js/src/features/human-resouce/components/LocationAssignForm.tsx
  js/src/features/human-resouce/components/Profile.tsx
  js/src/features/human-resouce/components/Vacations.tsx
  js/src/features/human-resouce/epics.ts
  js/src/features/human-resouce/reducer.ts
  js/src/features/human-resouce/selectors.ts
  js/src/features/human-resouce/types.d.ts
  js/src/features/human-resouce/vacations.reducer.ts
  js/src/pages/HumanResources.tsx
  js/src/pages/UserDetails.tsx
  js/src/services/human-resource-api.ts
  js/src/utils/date.ts
Labels: frontend

#88 fix project role form, change project sidebar
  js/src/features/app/components/SiderMenu.tsx
  js/src/features/project/actions.ts
  js/src/features/project/components/ProjectHeaderMenu.tsx
  js/src/features/project/components/ProjectRoleForm.scss
  js/src/features/project/components/ProjectRoleForm.tsx
  js/src/features/project/components/ProjectRoleFormEditRoleName.tsx
  js/src/features/project/components/ProjectRoleFormTableWrapper.tsx
  js/src/features/project/components/ProjectRoleFormViewRoleName.tsx
  js/src/features/project/epics.ts
  js/src/features/project/project.reducer.ts
  js/src/features/project/selectors.ts
  js/src/features/project/types.d.ts
  js/src/hooks/useClearState.ts
  js/src/layouts/Project.scss
  js/src/layouts/Project.tsx
  js/src/pages/ProjectPage.tsx
  js/src/pages/ProjectRolePage.tsx
  js/src/services/project-api.ts
Labels: frontend

#95 add listing of all user-locations for user #67
  build.gradle.kts
  doc/Location.md
  src/main/kotlin/io/easybreezy/hr/api/Router.kt
  src/main/kotlin/io/easybreezy/hr/api/controller/LocationController.kt
  src/main/kotlin/io/easybreezy/hr/application/absence/queryobject/Absence.kt
  src/main/kotlin/io/easybreezy/hr/application/calendar/queryobject/Holiday.kt
  src/main/kotlin/io/easybreezy/hr/application/location/queryobject/UserLocation.kt
  src/test/kotlin/io/easybreezy/hr/api/controller/LocationControllerTest.kt
Labels: backend
