Repository turbomates/easybreezy, pull requests merged in 2020-05, with the labels that each got.

#92 Absences CRUD
  js/src/constants.ts
  js/src/features/human-resouce/absences.reducer.ts
  js/src/features/human-resouce/actions.ts
  js/src/features/human-resouce/components/Absence/AbcenceListItem.tsx
  js/src/features/human-resouce/components/Absence/AbsenceForm.tsx
  js/src/features/human-resouce/components/Absence/AbsencesCard.tsx
  js/src/features/human-resouce/components/Absence/absence.helper.ts
  js/src/features/human-resouce/epics.ts
  js/src/features/human-resouce/selectors.ts
  js/src/features/human-resouce/types.d.ts
  js/src/pages/UserDetails.tsx
  js/src/services/human-resource-api.ts
Labels: frontend

#100 fix jwt auth and activities checking
  src/main/kotlin/io/easybreezy/infrastructure/ktor/auth/Authorization.kt
  src/main/kotlin/io/easybreezy/user/infrastructure/auth/UserProvider.kt
Labels: bug

#99 fix user location
  js/src/features/human-resouce/components/EmployeeLocationEditForm.tsx
  js/src/features/human-resouce/components/EmployeeLocationList.tsx
  js/src/features/human-resouce/components/LocationAssignForm.tsx
  js/src/features/location/types.d.ts
  js/src/services/location-api.ts
Labels: frontend

#104 user locations intersections #96
  doc/Location.md
  src/main/kotlin/io/easybreezy/application/Main.kt
  src/main/kotlin/io/easybreezy/hr/api/Router.kt
  src/main/kotlin/io/easybreezy/hr/api/controller/LocationController.kt
  src/main/kotlin/io/easybreezy/hr/application/location/Handler.kt
  src/main/kotlin/io/easybreezy/hr/application/location/Validation.kt
  src/main/kotlin/io/easybreezy/hr/application/location/queryobject/UserLocation.kt
  src/main/kotlin/io/easybreezy/hr/infrastructure/UserLocationRepository.kt
  src/main/kotlin/io/easybreezy/hr/model/absence/Absence.kt
  src/main/kotlin/io/easybreezy/hr/model/location/Exceptions.kt
  src/main/kotlin/io/easybreezy/hr/model/location/UserLocation.kt
  src/main/kotlin/io/easybreezy/infrastructure/ktor/Exceptions.kt
  src/main/kotlin/io/easybreezy/infrastructure/ktor/Response.kt
  src/main/kotlin/io/easybreezy/infrastructure/serialization/InferSerializer.kt
  src/main/kotlin/io/easybreezy/infrastructure/serialization/LocalDateSerializer.kt
  src/main/kotlin/io/easybreezy/user/application/Validation.kt
  src/main/kotlin/io/easybreezy/user/model/User.kt
  src/test/kotlin/io/easybreezy/hr/RecordsFactory.kt
  src/test/kotlin/io/easybreezy/hr/api/controller/LocationControllerTest.kt
Labels: bug

#116 users and employees listings #63
  src/main/kotlin/io/easybreezy/hr/application/location/queryobject/UserLocation.kt
  src/main/kotlin/io/easybreezy/hr/model/hr/Employee.kt
  src/main/kotlin/io/easybreezy/infrastructure/event/employee/Fired.kt
  src/main/kotlin/io/easybreezy/user/UserModule.kt
  src/main/kotlin/io/easybreezy/user/api/Router.kt
  src/main/kotlin/io/easybreezy/user/api/controller/UserController.kt
  src/main/kotlin/io/easybreezy/user/application/UpdateContacts.kt
  src/main/kotlin/io/easybreezy/user/application/command/Archive.kt
  src/main/kotlin/io/easybreezy/user/application/command/Confirm.kt
  src/main/kotlin/io/easybreezy/user/application/command/Create.kt
  src/main/kotlin/io/easybreezy/user/application/command/Handler.kt
  src/main/kotlin/io/easybreezy/user/application/command/Invite.kt
  src/main/kotlin/io/easybreezy/user/application/command/UpdateActivities.kt
  src/main/kotlin/io/easybreezy/user/application/command/UpdateContacts.kt
  src/main/kotlin/io/easybreezy/user/application/command/Validation.kt
  src/main/kotlin/io/easybreezy/user/application/subscriber/EmployeeSubscriber.kt
  src/main/kotlin/io/easybreezy/user/infrastructure/auth/UserProvider.kt
  src/main/kotlin/io/easybreezy/user/model/User.kt
  src/migrations/kotlin/io/easybreezy/migrations/V20200506140548__ChangeUserStatuses.kt
  src/test/kotlin/io/easybreezy/user/api/controller/application/ValidationTest.kt
Labels: backend

#101 fix project
  js/src/features/project/components/ProjectDescription.tsx
  js/src/features/project/components/ProjectDescriptionForm.tsx
  js/src/features/project/components/ProjectRoleForm.tsx
  js/src/features/project/components/ProjectRoleFormEditRoleName.tsx
  js/src/features/project/components/ProjectRoleFormTableWrapper.tsx
  js/src/features/project/components/ProjectRoleFormViewRoleName.tsx
  js/src/features/project/components/ProjectSlug.tsx
  js/src/features/project/components/ProjectSlugForm.tsx
  js/src/pages/ProjectPage.tsx
Labels: frontend

#112 add list of teams
  js/src/Routes.tsx
  js/src/features/project/components/ProjectHeaderMenu.tsx
  js/src/features/project/components/ProjectTeamsList.tsx
  js/src/features/project/components/ProjectTeamsListItem.tsx
  js/src/pages/ProjectTeamsPage.tsx
Labels: frontend

#119 Add create team
  js/src/features/project/actions.ts
  js/src/features/project/components/ProjectTeamsCreateForm.tsx
  js/src/features/project/epics.ts
  js/src/features/project/project.reducer.ts
  js/src/features/project/selectors.ts
  js/src/features/project/types.d.ts
  js/src/pages/ProjectTeamsPage.tsx
  js/src/services/index.ts
  js/src/services/team-api.ts
Labels: frontend

#117 Refactor account #103
  js/src/components/Paging.css
  js/src/components/Paging.scss
  js/src/components/Paging.tsx
  js/src/features/human-resouce/absences.reducer.ts
  js/src/features/human-resouce/actions.ts
  js/src/features/human-resouce/components/Absence/AbcenceListItem.tsx
  js/src/features/human-resouce/components/Absence/AbsenceForm.tsx
  js/src/features/human-resouce/components/Absence/AbsencesCard.tsx
  js/src/features/human-resouce/components/ContactsForm.scss
  js/src/features/human-resouce/components/ContactsForm.tsx
  js/src/features/human-resouce/components/EmployeeLocation/EmployeeLocationEditForm.tsx
  js/src/features/human-resouce/components/EmployeeLocation/EmployeeLocationList.tsx
  js/src/features/human-resouce/components/EmployeeLocation/EmployeeLocationListInner.tsx
  js/src/features/human-resouce/components/EmployeeLocation/EmployeeLocationsCard.scss
  js/src/features/human-resouce/components/EmployeeLocation/EmployeeLocationsCard.tsx
  js/src/features/human-resouce/components/EmployeeLocation/LocationAssignForm.tsx
  js/src/features/human-resouce/components/EmployeeLocation/helper.ts
  js/src/features/human-resouce/components/EmployeeLocationListInner.tsx
  js/src/features/human-resouce/components/Note/NoteForm.tsx
  js/src/features/human-resouce/components/Note/Notes.tsx
  js/src/features/human-resouce/components/Note/NotesCard.tsx
  js/src/features/human-resouce/components/NoteForm.tsx
  js/src/features/human-resouce/components/Position/PositionForm.tsx
  js/src/features/human-resouce/components/Position/Positions.tsx
  js/src/features/human-resouce/components/Position/PositionsCard.tsx
  js/src/features/human-resouce/components/PositionForm.tsx
  js/src/features/human-resouce/components/Salary/Salaries.tsx
  js/src/features/human-resouce/components/Salary/SalariesCard.tsx
  js/src/features/human-resouce/components/Salary/SalaryCard.scss
  js/src/features/human-resouce/components/Salary/SalaryForm.tsx
  js/src/features/human-resouce/components/SalaryForm.tsx
  js/src/features/human-resouce/components/Vacations.tsx
  js/src/features/human-resouce/details.reducer.ts
  js/src/features/human-resouce/epics.ts
  js/src/features/human-resouce/selectors.ts
  js/src/features/human-resouce/types.d.ts
  js/src/features/location/types.d.ts
  js/src/features/project/components/ProjectList.tsx
  js/src/pages/UserDetails.tsx
  js/src/services/human-resource-api.ts
  js/src/services/location-api.ts
  js/src/utils/error.ts
Labels: frontend

#122 add team members list
  js/src/Routes.tsx
  js/src/features/project/actions.ts
  js/src/features/project/components/Team/TeamMembersList.tsx
  js/src/features/project/components/Team/TeamMembersListItem.tsx
  js/src/features/project/epics.ts
  js/src/features/project/helpers.ts
  js/src/features/project/project.reducer.ts
  js/src/features/project/projects.reducer.ts
  js/src/features/project/reducer.ts
  js/src/features/project/selectors.ts
  js/src/features/project/team.reducer.ts
  js/src/features/project/types.d.ts
  js/src/pages/ProjectTeamPage.tsx
  js/src/pages/ProjectTeamsPage.tsx
  js/src/services/team-api.ts
Labels: frontend

#125 fix project epic
  js/src/features/project/epics.ts
Labels: frontend

#126 Add features for project team
  js/src/Routes.tsx
  js/src/features/project/actions.ts
  js/src/features/project/components/ProjectCreateForm.tsx
  js/src/features/project/components/ProjectDescription.tsx
  js/src/features/project/components/ProjectDescriptionForm.tsx
  js/src/features/project/components/ProjectHeaderMenu.tsx
  js/src/features/project/components/ProjectList.tsx
  js/src/features/project/components/ProjectRoleForm.tsx
  js/src/features/project/components/ProjectRoleFormEditRoleName.tsx
  js/src/features/project/components/ProjectRoleFormTableWrapper.tsx
  js/src/features/project/components/ProjectRoleFormViewRoleName.tsx
  js/src/features/project/components/ProjectSlug.tsx
  js/src/features/project/components/ProjectSlugForm.tsx
  js/src/features/project/components/ProjectStatusForm.tsx
  js/src/features/project/components/ProjectTeamsCreateForm.tsx
  js/src/features/project/components/ProjectTeamsList.tsx
  js/src/features/project/components/ProjectTeamsListItem.tsx
  js/src/features/project/components/Team/TeamChangeStatus.scss
  js/src/features/project/components/Team/TeamChangeStatus.tsx
  js/src/features/project/components/Team/TeamMembersList.tsx
  js/src/features/project/components/Team/TeamMembersListItem.tsx
  js/src/features/project/components/Team/TeamNewMemberForm.tsx
  js/src/features/project/epics.ts
  js/src/features/project/helpers.ts
  js/src/features/project/project.reducer.ts
  js/src/features/project/projects.reducer.ts
  js/src/features/project/selectors.ts
  js/src/features/project/team.reducer.ts
  js/src/features/project/types.d.ts
  js/src/pages/ProjectPage.tsx
  js/src/pages/ProjectRolePage.tsx
  js/src/pages/ProjectTeamPage.tsx
  js/src/pages/ProjectTeamsPage.tsx
  js/src/pages/ProjectsPage.tsx
  js/src/services/project-api.ts
  js/src/services/team-api.ts
  js/src/services/types.d.ts
Labels: frontend

#129 21 openapi
  build.gradle.kts
  buildSrc/src/main/kotlin/Configs.kt
  src/main/kotlin/io/easybreezy/application/Main.kt
  src/main/kotlin/io/easybreezy/hr/api/Router.kt
  src/main/kotlin/io/easybreezy/infrastructure/ktor/Response.kt
  src/main/kotlin/io/easybreezy/infrastructure/ktor/Router.kt
  src/main/kotlin/io/easybreezy/infrastructure/ktor/openapi/DescriptionBuilder.kt
  src/main/kotlin/io/easybreezy/integration/openapi/OpenAPI.kt
  src/main/kotlin/io/easybreezy/integration/openapi/OpenApiKType.kt
  src/main/kotlin/io/easybreezy/integration/openapi/ktor/OpenApi.kt
  src/main/kotlin/io/easybreezy/integration/openapi/ktor/Router.kt
  src/main/kotlin/io/easybreezy/integration/openapi/spec/Components.kt
  src/main/kotlin/io/easybreezy/integration/openapi/spec/Root.kt
  src/main/kotlin/io/easybreezy/integration/openapi/spec/ServerObject.kt
  src/main/kotlin/io/easybreezy/project/api/Router.kt
  src/main/kotlin/io/easybreezy/project/application/project/command/Validation.kt
  src/main/kotlin/io/easybreezy/user/api/Router.kt
  src/main/kotlin/io/easybreezy/user/api/interceptor/Auth.kt
  src/test/kotlin/io/easybreezy/TestApiEngine.kt
Labels: backend

#138 fix project
  js/src/features/human-resouce/absences.reducer.ts
  js/src/features/human-resouce/details.reducer.ts
  js/src/features/human-resouce/location.reducer.ts
  js/src/features/location/reducer.ts
  js/src/features/notification/actions.ts
  js/src/features/notification/epics.ts
  js/src/features/project/actions.ts
  js/src/features/project/components/Project/NewProjectForm.tsx
  js/src/features/project/components/Project/ProjectDescription.tsx
  js/src/features/project/components/Project/ProjectDescriptionForm.tsx
  js/src/features/project/components/Project/ProjectList.tsx
  js/src/features/project/components/Project/ProjectSlug.tsx
  js/src/features/project/components/Project/ProjectSlugForm.tsx
  js/src/features/project/components/Project/ProjectStatusForm.scss
  js/src/features/project/components/Project/ProjectStatusForm.tsx
  js/src/features/project/components/Role/RoleForm.scss
  js/src/features/project/components/Role/RoleForm.tsx
  js/src/features/project/components/Role/RoleFormEditRoleName.tsx
  js/src/features/project/components/Role/RoleFormTable.tsx
  js/src/features/project/components/Role/RoleFormViewRoleName.tsx
  js/src/features/project/components/Team/NewTeamForm.tsx
  js/src/features/project/components/Team/TeamList.tsx
  js/src/features/project/components/Team/TeamListItem.tsx
  js/src/features/project/components/Team/TeamNewMemberForm.tsx
  js/src/features/project/epics.ts
  js/src/features/project/project.reducer.ts
  js/src/features/project/projects.reducer.ts
  js/src/features/project/selectors.ts
  js/src/features/project/team.reducer.ts
  js/src/pages/ProjectPage.tsx
  js/src/pages/ProjectRolePage.tsx
  js/src/pages/ProjectTeamPage.tsx
  js/src/pages/ProjectTeamsPage.tsx
  js/src/pages/ProjectsPage.tsx
  js/src/services/project-api.ts
  js/src/services/team-api.ts
  js/src/store/root-action.ts
  js/src/store/root-epic.ts
  js/src/utils/error.ts
  js/src/utils/errors.ts
Labels: frontend

#128 Issue parser
  README.md
  doc/issue_language.md
  src/main/kotlin/io/easybreezy/project/ProjectModule.kt
  src/main/kotlin/io/easybreezy/project/api/Router.kt
  src/main/kotlin/io/easybreezy/project/api/controller/IssueController.kt
  src/main/kotlin/io/easybreezy/project/application/issue/command/Handler.kt
  src/main/kotlin/io/easybreezy/project/application/issue/command/Parser.kt
  src/main/kotlin/io/easybreezy/project/application/issue/command/StatusWorkflow.kt
  src/main/kotlin/io/easybreezy/project/application/issue/command/language/LanguageTranslator.kt
  src/main/kotlin/io/easybreezy/project/application/issue/command/language/Normalizer.kt
  src/main/kotlin/io/easybreezy/project/application/issue/command/language/Parser.kt
  src/main/kotlin/io/easybreezy/project/application/issue/command/language/element/CategoryNormalizer.kt
  src/main/kotlin/io/easybreezy/project/application/issue/command/language/element/ElementNormalizer.kt
  src/main/kotlin/io/easybreezy/project/application/issue/command/language/element/LabelNormalizer.kt
  src/main/kotlin/io/easybreezy/project/application/issue/command/language/element/MembersNormalize.kt
  src/main/kotlin/io/easybreezy/project/application/issue/command/language/element/PriorityNormalizer.kt
  src/main/kotlin/io/easybreezy/project/application/issue/queryobject/Issue.kt
  src/main/kotlin/io/easybreezy/project/application/project/queryobject/Settings.kt
  src/main/kotlin/io/easybreezy/project/infrastructure/LabelRepository.kt
  src/main/kotlin/io/easybreezy/project/model/issue/Issue.kt
  src/main/kotlin/io/easybreezy/project/model/issue/Label.kt
  src/main/kotlin/io/easybreezy/project/model/issue/Priority.kt
  src/main/kotlin/io/easybreezy/user/model/User.kt
  src/main/resources/issue-parser/en.settings.json
  src/main/resources/issue-parser/ru.settings.json
  src/migrations/kotlin/io/easybreezy/migrations/V20200511125540__Usernames.kt
  src/migrations/kotlin/io/easybreezy/migrations/V20200512092106__NeutralPriorityColor.kt
  src/migrations/kotlin/io/easybreezy/migrations/V20200518154035__IssueLabelsDue.kt
  src/test/kotlin/io/easybreezy/project/api/controller/IssueControllerTest.kt
  src/test/kotlin/io/easybreezy/project/application/issue/command/ParserTest.kt
Labels: backend
